export const REQUEST_FOR_PRODUCT_DETAIL_LIST = "REQUEST_FOR_PRODUCT_DETAIL_LIST"
export const REQUEST_FOR_PRODUCT_DETAIL_SUCCESS = "REQUEST_FOR_PRODUCT_DETAIL_SUCCESS"
export const REQUEST_FOR_PRODUCT_DETAIL_FAIL = "REQUEST_FOR_PRODUCT_DETAIL_FAIL"

export const REQUEST_FOR_PRODUCT_LIST = "REQUEST_FOR_PRODUCT_LIST"
export const REQUEST_FOR_PRODUCT_SUCCESS = "REQUEST_FOR_PRODUCT_SUCCESS"
export const REQUEST_FOR_PRODUCT_FAIL = "REQUEST_FOR_PRODUCT_FAIL"


export const REQUEST_FOR_SLIDERIMAGE_LIST = "REQUEST_FOR_SLIDERIMAGE_LIST"
export const REQUEST_FOR_SLIDERIMAGE_SUCCESS = "REQUEST_FOR_SLIDERIMAGE_SUCCESS"
export const REQUEST_FOR_SLIDERIMAGE_FAIL = "REQUEST_FOR_SLIDERIMAGE_FAIL"